Team3_Project/Team3_Project/Controllers/BrowseController.cs
namespace Team3_Project.Controllers {
	public class BrowseController : System.Web.Mvc.Controller {
		public System.Web.Mvc.ActionResult BrowseMovies() {
			Databases.memdixyp_film.list[] list = Databases.memdixyp_film.list.random_lists();
			System.Int32 index = list.Length;
			Databases.memdixyp_film.view_list[][] view_list = new Databases.memdixyp_film.view_list[index][];
			while (index > 0) {
				index -= 1;
				view_list[index] = Databases.memdixyp_film.view_list.show_movie_list(list[index].identifier);
			}
			this.ViewBag.list = list;
			this.ViewBag.view_list = view_list;
			return this.View();
		}
		public System.Web.Mvc.ActionResult SearchMovies(System.String Title) {
			System.Collections.Generic.List<Helpers.Watchable> resultList = new System.Collections.Generic.List<Helpers.Watchable>();
			Helpers.ODBAPI api = new Helpers.ODBAPI();
            for(System.Int32 i = 1; i<5; i++)
            {
                System.String response = api.GetAPIinfo("s=" + Title + "&page=" + i);
                api.ParseSearch(resultList, response);
            }

			this.ViewBag.searchResults = resultList;
			return this.View();
		}
	}
}

Team3_Project/Team3_Project/Controllers/MovieController.cs
namespace Team3_Project.Controllers {
	public class MovieController : System.Web.Mvc.Controller {
		// GET: Movie
		public System.Web.Mvc.ActionResult MoviePage(System.String id = "tt0000001") {
			Helpers.ODBAPI api = new Helpers.ODBAPI();
			System.String response = api.GetAPIinfo("i=" + id);
			Helpers.Watchable watchable = Newtonsoft.Json.JsonConvert.DeserializeObject<Helpers.Watchable>(response);
			this.ViewBag.json = watchable;
			this.ViewBag.list = Databases.memdixyp_film.list.list_by_user(System.Convert.ToInt32(this.Session["UserId"]));
			return this.View();
		}
	}
}

Team3_Project/Team3_Project/Views/Browse/BrowseMovies.cshtml
@{
	this.Layout = "/Views/Shared/_Layout.cshtml";
	this.ViewBag.Title = "BrowseMovies";
	this.ViewBag.css = new System.String[] { "w3" };
}			<div class="PageHeader">
				<div class="buttonNav">
					<p>Browse/Search for Movies</p>
				</div>
				<div class="buttonNav buttonNav1">
					<form action="~/Profile/Profile" method="get">
						<div class="form-row">
							<div>
								<button id="Profile" type="submit" class="w3-btn w3-black w3-hover-green w3-round-xxlarge w3-large">Profile Page</button>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="textSearch">
				<p>Please enter the start of the movie name or the entire movie name and click search</p>
@using (Html.BeginForm("SearchMovies", "Browse", FormMethod.Get)) {
					<input type="text" name="title" id="title" />
					<button class="w3-btn w3-black w3-hover-green w3-round-xxlarge w3-large" type="submit">Search</button>
}			</div>
			<div class="CurratedListsTable">
				<table class="resultTable1 w3-col l12">
@for (System.Int32 index_a = 0; index_a < this.ViewBag.list.Length; index_a += 1) {
					<tr class="listTitle">
						<td >
							@this.ViewBag.list[index_a].name
						</td>
					</tr>
					<tr class="listMovies">
						<td>
@for (System.Int32 index_b = 0; index_b < System.Math.Min(5 , this.ViewBag.view_list[index_a].Length); index_b += 1) {
							<a href="/Movie/MoviePage/@this.ViewBag.view_list[index_a][index_b].tconst" class="elements">
								<img alt="@this.ViewBag.view_list[index_a][index_b].primaryTitle" class="movieposter1 w3-third" src="@this.ViewBag.view_list[index_a][index_b].poster" />
							</a>
}						</td>
					</tr>
}				</table>
			</div>

Team3_Project/Team3_Project/Views/Browse/SearchMovies.cshtml
@{
	this.Layout = "/Views/Shared/_Layout.cshtml";
	this.ViewBag.Title = "SearchMovies";
	this.ViewBag.css = new System.String[] { "w3" };
}			<div class="PageHeader">
				<p>Search Results</p>
			</div>
			<div class="SearchResults w3-col l12">
				<table class="resultTable w3-col l12">
					<tr>
@foreach (var movie in ViewBag.searchResults) {
	if (movie.poster == "N/A") {
							movie.poster = "../Images/noimageavailable.png";
}						<td>
							<a href="@Url.Action( "MoviePage", "Movie", new { ID = movie.imdbID.Trim() })" class="elements"><img src=@movie.poster alt=@movie.title class="movieposter w3-third" /></a>								  
						</td>
}					</tr>
				</table>
			</div>